### ISSUE TITLE
Facing issue while using your docker image for ssm while utility after install works perfectly

### ISSUE THREAD

**Issue by gauravjain811** [binxio/ssm-get-parameter#1]
Hello ,

could not find program /bin/bash on path, exec: "/bin/bash": stat /bin/bash: no such file or directory -> facing issue while using ssm in dockerfile for entry point... could you give any hint ?

used as per your stated example as below :

FROM binxio/ssm-get-parameter

FROM alpine:3.6
COPY --from=0 /ssm-get-parameter /usr/local/bin/

ENV PGPASSWORD=ssm:///postgres/root/password
ENTRYPOINT [ "/usr/local/bin/ssm-get-parameter"]
CMD [ "/bin/bash", "-c", "echo $PGPASSWORD"]
Regards,
Gaurav

**Comment by mvanholsteijn** [comment]
alpine does not have bash installed by default.  Use:

```
CMD [ "/bin/sh", "-c", "echo $PGPASSWORD"]
```

**Comment by mvanholsteijn** [comment]
fixed in readme. Thank you!
