### ISSUE TITLE
MissingRegion: could not find region configuration despite AWS_DEFAULT_REGION is set

### ISSUE THREAD

**Issue by dmalko-airslate** [binxio/ssm-get-parameter#3]
Thank you for your tool!
Trying to get ssm parameter, but I getting an error 
`MissingRegion: could not find region configuration`

Is this tool working with AIM Role?

This commands that I used
```
export AWS_DEFAULT_REGION="us-east-1"
root:~# export TEST=ssm:///test
root:~# ssm-get-parameter bash -c 'echo $TEST'
2022/09/21 06:53:08 ERROR: failed to get parameter TEST, MissingRegion: could not find region configuration, no default value available
root:~# ssm-get-parameter -verbose -name test
2022/09/21 06:53:18 ERROR: failed to get parameter, MissingRegion: could not find region configuration
```

But I can get this parameter using aws cli
```
aws ssm get-parameter --name "test"
{
    "Parameter": {
        "Name": "test",
        "Type": "String",
        "Value": "test",
        "Version": 1,
        "LastModifiedDate": "2018-09-29T05:28:33.467000+00:00",
        "ARN": "arn:aws:ssm:us-east-1:00000000:parameter/test"
    }
}
```

**Comment by mvanholsteijn** [comment]
Which version are you using? I tested it with 0.4.1 and it does work.  @vecchp made a change to honour the AWS shared configuration settings, including the AWS_DEFAULT_REGION a few months ago.

**Comment by dmalko-airslate** [comment]
Thank you for your answer. I am using ECS cluster based on EC2 and I need to use IAM Roles associated to EC2 instance. As you see I can make aws ssm get-parameter using IAM Roles, but I see an error when trying your tool.
I am copying binary ssm-get-parameter from your latest docker image.
Please, ask if you need'll additional information.
At this moment, I am using role with this configuration.

```
{
            "Effect": "Allow",
            "Action": [
                "ssm:*",
                "ssmmessages:*",
                "ec2messages:*"
            ],
            "Resource": "*"
        }
```

**Comment by dmalko-airslate** [comment]
I don't see where are you assuming sts role. For eg: https://github.com/aws/aws-sdk-go/issues/801#issuecomment-935701212

**Comment by mvanholsteijn** [comment]
Does it work when you add the environment variable AWS_SDK_LOAD_CONFIG=1?

**Comment by dmalko-airslate** [comment]
Yes, it's working! I didn't think about it.
Thanks a lot!
